### ISSUE TITLE
appMessagesGetIsSupported frequently returns 0 when connection to Pebble classic from iOS SDK 3.0

### ISSUE THREAD

**Issue by jeradesign** [pebble/pebble-ios-sdk#9] opened 2015-10-27 03:56 UTC
Once watchDidConnect callback happens, call to appMessagesGetIsSupported appears to time out after 20 seconds and return 0.

See log:

2015-10-26 20:52:43.256 WristVision[652:20385] pebbleCentral:<PBPebbleCentral: 0x125e44810> watchDidConnect:<PBWatch: 0x125e452c0, Pebble C260, 33J0110FC260, iAP> isNew:0
2015-10-26 20:52:43.257 WristVision[652:20385] connectPebble
2015-10-26 20:53:03.273 WristVision[652:20385] appMessagesGetIsSupported callback, PBWatch = <PBWatch: 0x125e452c0, Pebble C260, 33J0110FC260, iAP>, isAppMessagesSupported = 0

**Comment by drodriguez** [comment] 2015-10-27 18:35
This problem and #7 are probably related.

You don’t specify if your iOS device was running iOS 9, but I will suppose you were. I can see here that you were using either a Pebble or a Pebble Steel, which will be running the 2.x FW.

Several people have found that we seem to have sporadic problems in iOS 9 with the 2.x FW (ref: https://forums.getpebble.com/discussion/comment/156273). Seems that changes in PebbleKit 3.0 makes those problems even more visible.

Without going into detail, in some occasions, in iOS 9, iOS seems to report the connection (Classic transport) as connected, but only the messages from the watch to the phone are correctly transmitted, the messages from the phone to the watch are lost somewhere in the iOS code. Sometimes closing the session or restarting the watch BT seems to “fix” the issue. Since in PebbleKit 3.0 we need to exchange some messages before being able to send anything (we need to discover if the watch is able to do 8KB messages and such), many of our messages “timeout” (we send something, the watch never receives it, and we don’t receive a response).

In the forum thread referenced above we are trying to come up with some solutions that sometimes work. Care to try and share your experiences?

We are trying to come with a solution, but we are still trying to understand which change in iOS 9 broke our communications (and why we are not seeing nothing wrong in the PebbleKit side). The good thing is that our FW 3.0 implementation or the LE transport doesn’t seem to be able to reproduce the problem.

**Comment by yageek** [comment] 2015-11-06 09:24
Any news about when the FW3.0 will be available ?

**Comment by drodriguez** [comment] 2015-11-06 19:00
The only thing we can say is “soon” (sorry we cannot be more specific, and sorry that we are focusing into fixing it this way).

**Comment by yageek** [comment] 2015-11-09 08:59
Ok. should we create a list about the concerned devices or do you have already enough informations ?

**Comment by drodriguez** [comment] 2015-11-10 19:40
“concerned devices”? What do you mean?

**Comment by yageek** [comment] 2015-11-11 05:07
I mean which models with which firmware issue this bug.

**Comment by drodriguez** [comment] 2015-11-11 18:12
As far as we know, any watch with 2.x FW and using iOS 9.x might hit this bug. We are working in a workaround until the final FW 3.x arrives for those watches.

**Comment by mathiasAichinger** [comment] 2015-11-25 09:31
I have the same problem with the Classic Pebble.

**Comment by mrcljx** [comment] 2015-12-09 01:20
Hi everyone. we included a workaround in PebbleKit `3.1.0` which is available now. Thanks for reporting this. :+1:

**Closed as completed by mrcljx** 2015-12-09 01:20 UTC
